#!/bin/bash
#
# Script to encrypt / decrypt secrets.
#

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions.sh"

# Default values
SECRET_FILE=buildSrc/src/main/kotlin/Secrets.kt

# Functions
function usage {
    echo -e "Usage: ${0} [COMMAND]"
    echo -e "Commands:"
    echo -e " decrypt"
    echo -e " encrypt"
    exit 1
}

# Command-line arguments
while [[ $# -gt 0 ]] ; do
    key="$1"
    case $key in
    decrypt)
        approve "Decrypting ${SECRET_FILE}.enc"
        openssl enc -d -aes-256-cbc -in ${SECRET_FILE}.enc -out ${SECRET_FILE}
        ;;
    encrypt)
        approve "Encrypting ${SECRET_FILE}"
        openssl enc -aes-256-cbc -salt -in ${SECRET_FILE} -out ${SECRET_FILE}.enc
        ;;
    -h|--help)
        usage
        ;;
    *)
        warn "Unknown option: ${key}"
        usage
        ;;
    esac
    shift # past argument or value
done
